export const items = [
  { name: '종교', href: `/tag/종교` },
  { name: '음식', href: '/tag/음식' },
  { name: '운동', href: '/tag/운동' },
  { name: '건강관리', href: '/tag/건강관리' },
  { name: '여행', href: '/tag/여행' },
  { name: 'DIY', href: '/tag/DIY' },
  { name: '건축', href: '/tag/건축' },
  { name: '인테리어', href: '/tag/인테리어' },
  { name: '식물', href: '/tag/식물' },
  { name: '자연', href: '/tag/자연' },
  { name: '환경', href: '/tag/환경' },
  { name: '문화생활', href: '/tag/문화생활' },
  { name: '사회', href: '/tag/사회' },
  { name: '역사', href: '/tag/역사' },
  { name: '자기개발', href: '/tag/자기개발' },
  { name: '금융', href: '/tag/금융' },
  { name: '경제', href: '/tag/경제' },
  { name: '음악', href: '/tag/음악' },
  { name: '미술', href: '/tag/미술' },
  { name: '신화', href: '/tag/신화' },
  { name: '미스테리', href: '/tag/미스테리' },
  { name: '지구과학', href: '/tag/지구과학' },
  { name: '의학', href: '/tag/의학' },
  { name: '컴퓨터', href: '/tag/컴퓨터' },
  { name: '프로그래밍', href: '/tag/프로그래밍' },
  { name: '쇼핑', href: '/tag/쇼핑' },
];
