export const dummyTags = [
  { id: 1, name: '음식', posts: [] },
  { id: 2, name: '운동', posts: [] },
  { id: 3, name: '여행', posts: [] },
  { id: 4, name: '사회', posts: [] },
  { id: 5, name: '역사', posts: [] },
  { id: 6, name: '금융', posts: [] },
  { id: 7, name: '경제', posts: [] },
  { id: 8, name: '기술', posts: [] },
  { id: 9, name: '발전', posts: [] },
  { id: 10, name: '회계', posts: [] },
  { id: 11, name: '환율', posts: [] },
  { id: 12, name: '컴퓨터', posts: [] },
  { id: 13, name: '프로그래밍', posts: [] },
  { id: 14, name: '앱', posts: [] },
  { id: 15, name: '미용', posts: [] },
  { id: 16, name: '트렌드', posts: [] },
  { id: 17, name: '자연재해', posts: [] },
  { id: 18, name: '부동산', posts: [] },
  { id: 19, name: '지리', posts: [] },
  { id: 20, name: '땅', posts: [] },
  { id: 21, name: '정치', posts: [] },
  { id: 22, name: '뉴스', posts: [] },
  { id: 23, name: 'AI', posts: [] },
];
