export const items = [
  { name: '종교', href: `/tag/종교` },
  { name: '요리', href: '/tag/요리' },
  { name: '다이어트', href: '/tag/다이어트' },
  { name: '운동', href: '/tag/운동' },
  { name: '건강', href: '/tag/건강' },
  { name: '웰빙', href: '/tag/웰빙' },
  { name: '여행', href: '/tag/여행' },
  { name: '라이프스타일', href: '/tag/라이프스타일' },
  { name: 'DIY', href: '/tag/DIY' },
  { name: '문화생활', href: '/tag/문화생활' },
  { name: '사회', href: '/tag/사회' },
  { name: '역사', href: '/tag/역사' },
  { name: '자기개발', href: '/tag/자기개발' },
  { name: '금융', href: '/tag/금융' },
  { name: '음악', href: '/tag/음악' },
  { name: '신화', href: '/tag/신화' },
  { name: '미스테리', href: '/tag/미스테리' },
];
