import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { ClientPage } from './components/client-page';
import './globals.css';

import Nav from './components/nav';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from './components/app-sidebar';
import { cookies } from 'next/headers';
import { getPosts } from './lib/actions/post';

const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'false';

  const posts = await getPosts();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar posts={posts} />
            <main>
              <SidebarTrigger className="bg-transparent hover:bg-transparent w-fit" />
              <Nav />
              <ClientPage> {children}</ClientPage>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
